# ==============================================
# WINDOWS RULES
# ==============================================

# Dims everything behind the launcher layer (fuzzel)
layerrule = match:namespace launcher, dim_around on

# Dims everything behind floating windows
windowrule = match:float 1, dim_around on

# Set bordercolor to red if window is fullscreen
windowrule = match:fullscreen 1, border_color rgb(a54848)

# Floating file manager (yazi)
windowrule {
	name = floating-filemanager
	match:class = float_filemanager
	float = on
	center = on
	size = (monitor_w*0.8) (monitor_h*0.8)
	stay_focused = on
	group = set
}

# Floating terminal
windowrule {
	name = floating-terminal
	match:class = float_terminal
	float = on
	center = on
	size =  (monitor_w*0.6) (monitor_h*0.6) 
	stay_focused = on
	group = set 
}


